# Generated by Django 4.1.3 on 2022-11-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JsonModel",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("verse_number", models.IntegerField()),
                ("verse_key", models.CharField(max_length=10)),
                ("hizb_number", models.IntegerField()),
                ("rub_el_hizb_number", models.IntegerField()),
                ("ruku_number", models.IntegerField()),
                ("manzil_number", models.IntegerField()),
                ("sajdah_number", models.IntegerField()),
                ("text_uthmani", models.CharField(max_length=2000)),
                ("chapter_id", models.IntegerField()),
                ("text_imlaei_simple", models.CharField(max_length=2000)),
                ("juz_number", models.IntegerField()),
                ("translations", models.JSONField()),
            ],
        ),
    ]
